# Generated by Django 5.0.6 on 2024-05-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('car_color', models.CharField(max_length=15)),
                ('car_make', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=500)),
                ('qty', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Being Made', 'Being Made'), ('Done', 'Done'), ('Picked Up', 'Picked Up'), ('On Its Way', 'On Its Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('delivery', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(max_length=1000)),
                ('time_placed', models.DateTimeField(auto_now_add=True)),
                ('driver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food_Items.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.SmallIntegerField()),
                ('tag', models.CharField(max_length=20)),
                ('spiciness', models.TextField()),
                ('special_instructions', models.CharField(max_length=500)),
                ('food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food_Items.fooditem')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food_Items.order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('likes', models.PositiveSmallIntegerField()),
                ('shares', models.PositiveSmallIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Items.customer')),
            ],
        ),
    ]
