# Generated by Django 5.0.6 on 2024-05-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
