# Generated by Django 5.0.6 on 2024-05-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0002_alter_customer_address_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
