# Generated by Django 5.0.6 on 2024-05-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0003_rename_driver_id_order_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='driver',
            new_name='driver_id',
        ),
    ]
