# Generated by Django 5.0.6 on 2024-05-23 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0004_rename_driver_order_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Food_Items.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
