# Generated by Django 5.0.6 on 2024-05-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0005_order_name_alter_order_special_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
