# Generated by Django 5.0.6 on 2024-05-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0008_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='special_instructions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='spiciness',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='tag',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
