# Generated by Django 5.0.6 on 2024-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0009_alter_order_details_special_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_item',
            field=models.ManyToManyField(through='Food_Items.Order_Details', to='Food_Items.fooditem'),
        ),
    ]
