# Generated by Django 5.0.6 on 2024-05-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0010_order_food_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food_item',
            new_name='food_items',
        ),
    ]
