# Generated by Django 5.0.6 on 2024-05-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0011_rename_food_item_order_food_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='food_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_id', to='Food_Items.fooditem'),
        ),
    ]
