# Generated by Django 5.0.6 on 2024-05-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0012_alter_order_details_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='food_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food_Items.fooditem'),
        ),
    ]
