# Generated by Django 5.0.6 on 2024-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0013_alter_order_details_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
