# Generated by Django 5.0.6 on 2024-05-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0014_fooditem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Drinks', 'Drinks')], max_length=20, null=True),
        ),
    ]
