# Generated by Django 5.0.6 on 2024-05-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0015_fooditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Driver'),
        ),
    ]
