# Generated by Django 5.0.6 on 2024-05-23 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0016_alter_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food_Items.driver', verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='spiciness',
            field=models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Mild', 'Mild'), ('Medium', 'Medium'), ('Hot', 'Hot'), ('Burn Yo Butthole', 'Burn Yo Butthole')], max_length=20, null=True),
        ),
    ]
