# Generated by Django 5.0.6 on 2024-05-24 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Items', '0017_alter_driver_name_alter_fooditem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food_Items.driver', verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Received', 'Received'), ('Being Made', 'Being Made'), ('Done', 'Done'), ('Picked Up', 'Picked Up'), ('On Its Way', 'On Its Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
